### ISSUE TITLE
Extruder Crashing into back of printer during AUTO_CALIBRATE.gcode

### ISSUE THREAD

**Issue by Jozer99** [aegean-odyssey/mpmd_marlin_1.1.x#42]
I've been running your 119r09 for quite a while, decided to upgrade to the latest 119r14.  I downloaded and flashed the correct firmware bin file for my printer (0001 AC FAN 10A).  

When I run the AUTO_CALIBRATE.gcode, the printer correctly homes itself twice, then the back axis goes all the way up, while the other two axes go all the way down, causing the extruder platform to crash into the back axis rails.  I figured out that the issue was resolved by running M502 before AUTO_CALIBRATE.gcode.  Evidently something in the saved settings from 119r09 was messing with 119r14's ability to correctly calibrate.  I recommend adding this to your setup instructions, or including an M502 in the AUTO_CALIBRATE.gcode script (or manually changing whatever particular geometry settings are the problem).

**Comment by aegean-odyssey** [comment]
Good to hear that you were able to get the printer and firmware working. 

It turns out that there is a specific callout in the release notes for your issue -- but in the release notes for `119r10`!  You are correct; the settings structure did change starting with `119r10` and your course of action is exactly the prescribed remedy.

Thank you for reporting your experience. We'll keep working at the documentation to get useful information where it's needed.
