### ISSUE TITLE
Control FAN

### ISSUE THREAD

**Issue by Electromente** [aegean-odyssey/mpmd_marlin_1.1.x#77]
Hi guys, 

Im using the 119r15 version and works excellent, the only issue is that Im trying with ABS and in many webpages recommended to put the heater fan off or set it at min value.

I'm using Cura slicer and set the Fan to 10% but looks like dont do anything.

Could you let me know if this setting really works or this printer cannot control it? 

as far as I remember, the Stock firmware dont took this configuration either.

Thanks for your great work.

**Comment by PurpleHullPeas** [comment]
You do not want to do that with the stock MPMD hot-end. Rotate the fan shroud upside down, so that the blower is point upwards into the air instead of on the print. 

The articles you have been reading are referring specifically to 3D printers that have [more than one fan on the hot-end](https://all3dp.com/2/3d-printer-fans-do-i-really-need-one/). One fan is typically used to cool the heatsink and heatbreak - in order to prevent clogs due to plastic melting into the throat (heat creep). The other fan, called a _part-cooling fan_, is used to cool the plastic as it comes out of the nozzle. The ABS recommendations are for turning off the _part-cooling_ fan, not the heat sink fan. 

The stock Monoprice Mini Delta has only one fan that serves both of those purposes. For ABS, you can either block the bottom of the fan duct from blowing on the nozzle or turn it upside down.

**Comment by Electromente** [comment]
Thanks to clarify it, I'm printing now in ABS with the normal position. Then I'll turn it upside down and print the same example to compare and let you know.

**Comment by Electromente** [comment]
I've made the change to the heater fan, the final piece is very hard and solid, but now I'm trying different temperatures to don't have small parts with spilled ABS hehe. Anyway, is a very good approach may be the critical parts printed without Fan and the smaller or so detailed pieces printed with Fan enables. (or just move on to PLA hehe)

![Tangled disassembled](https://user-images.githubusercontent.com/85633254/121703104-7adfd680-caa0-11eb-9660-85dfbd0188bd.jpeg)
![Tangles assembled](https://user-images.githubusercontent.com/85633254/121703111-7d423080-caa0-11eb-8ae3-8e6d28753a92.jpeg)
![Tangles assembled2](https://user-images.githubusercontent.com/85633254/121703113-7ddac700-caa0-11eb-8a7e-3621f1aa1f56.jpeg)

**Comment by Electromente** [comment]
Speaking about the details have no major differences between both Fan positions. just you must use middle or lower temperatures as ABS Support to avoid spilled of ABS.
