### ISSUE TITLE
Bizarre Behavior when Calibrating

### ISSUE THREAD

**Issue by gordsellar** [aegean-odyssey/mpmd_marlin_1.1.x#86]
I'm not sure what I'm doing wrong, but when I try install the latest version of the firmware on my MP Mini Delta, I get to the calibration stage and when I run AUTO_CALIBRATE.gcode, the printer tries to jam the extruder down and to the left (where I'm facing the panel of the machine with the display screen head-on). It jams it into that corner really hard! 

I've looked in the issues (the ones I can see) and don't see anyone describing that. I *can* see that there's a possibility I need to configure things differently based on it being a very early model, but I'm not sure that's the core of the problem at the moment.  

I've tried both -SM0001 and -SM1110 and the printer doesn't seem to be able to Home after either. Not really sure how to proceed: any suggestions? 

(And I did see the thing about it going haywire during calibration but I'm not sure this is really the same issue or not.) 

If you can't tell, I'm a bit out at sea with this, but trying to learn!

**Comment by mulcmu** [comment]
I had a similar crash that was caused by some old start gcode logic that used `G91` to enable relative positioning but didn't execute `G90` to restore absolute positioning.

Was printer just upgraded from stock firmware or was a prior version of `mpmd_marlin_1.1.x` working previously?

[Wiki](https://github.com/aegean-odyssey/mpmd_marlin_1.1.x/wiki/Which-Firmware%3f) has some steps for determining which variant.  Older machines likely need to run the `M92_XYZ57_E48.gcode` to load the 1/8 stepping values.

**Comment by gordsellar** [comment]
Ooops, I missed that note about older printers and needing to run M92_XYZ57_E48.gcode. That seems to have been the issue (I misunderstood the function of the code), and it's calibrating now. Whew! Thanks so much! 
Oh, and the printer was indeed just upgraded from stock firmware. It's the first time I'm installing mpmd_marlin on it. It seems to be working now, though the bed leveling routine in the wiki here wasn't quite enough for me to nail down all the problems. I'll keep looking. 
Thanks so much again for your help!
